/*  =========================================================================
    joe - generated layer of public API

    Copyright (c) the Contributors as noted in the AUTHORS file.       
    This file is part of CZMQ, the high-level C binding for 0MQ:       
    http://czmq.zeromq.org.                                            
                                                                       
    This Source Code Form is subject to the terms of the Mozilla Public
    License, v. 2.0. If a copy of the MPL was not distributed with this
    file, You can obtain one at http://mozilla.org/MPL/2.0/.           

################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
    =========================================================================
*/

#ifndef JOE_LIBRARY_H_INCLUDED
#define JOE_LIBRARY_H_INCLUDED

//  Set up environment for the application

//  External dependencies
#include <czmq.h>

//  JOE version macros for compile-time API detection
#define JOE_VERSION_MAJOR 0
#define JOE_VERSION_MINOR 1
#define JOE_VERSION_PATCH 0

#define JOE_MAKE_VERSION(major, minor, patch) \
    ((major) * 10000 + (minor) * 100 + (patch))
#define JOE_VERSION \
    JOE_MAKE_VERSION(JOE_VERSION_MAJOR, JOE_VERSION_MINOR, JOE_VERSION_PATCH)

#if defined (__WINDOWS__)
#   if defined JOE_STATIC
#       define JOE_EXPORT
#   elif defined JOE_INTERNAL_BUILD
#       if defined DLL_EXPORT
#           define JOE_EXPORT __declspec(dllexport)
#       else
#           define JOE_EXPORT
#       endif
#   elif defined JOE_EXPORTS
#       define JOE_EXPORT __declspec(dllexport)
#   else
#       define JOE_EXPORT __declspec(dllimport)
#   endif
#   define JOE_PRIVATE
#else
#   define JOE_EXPORT
#   if (defined __GNUC__ && __GNUC__ >= 4) || defined __INTEL_COMPILER
#       define JOE_PRIVATE __attribute__ ((visibility ("hidden")))
#   else
#       define JOE_PRIVATE
#   endif
#endif

//  Opaque class structures to allow forward references
//  These classes are stable or legacy and built in all releases
typedef struct _joe_server_t joe_server_t;
#define JOE_SERVER_T_DEFINED
typedef struct _joe_proto_t joe_proto_t;
#define JOE_PROTO_T_DEFINED


//  Public classes, each with its own header file
#include "joe_server.h"
#include "joe_proto.h"

#endif
/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
*/
